version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pli
      POSTGRES_PASSWORD: pli
      POSTGRES_DB: pli
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-12-18T18-04-18Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    image: node:20-alpine
    working_dir: /workspace
    command: sh -lc "corepack enable && pnpm install --frozen-lockfile && pnpm api:dev"
    environment:
      DATABASE_URL: postgres://pli:pli@postgres:5432/pli
      HOST: 0.0.0.0
      PORT: 4000
      PUBLIC_BASE_URL: http://localhost:8080
      PAYMENT_GATEWAY: mock
      PAYMENT_GATEWAY_BASE_URL: http://localhost:8080
      SESSION_SECRET: local-dev-secret
      CONTENT_STORAGE_ROOT: /workspace/.local-content
    volumes:
      - ..:/workspace
    depends_on:
      - postgres

  web:
    image: node:20-alpine
    working_dir: /workspace
    command: sh -lc "corepack enable && pnpm install --frozen-lockfile && pnpm dev -- --hostname 0.0.0.0 --port 3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
      NEXT_PUBLIC_WEB_BASE_URL: http://localhost:8080
    volumes:
      - ..:/workspace
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api

volumes:
  postgres_data:
  minio_data:
